title: vbphung
description: Jim's personal website
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
remote_theme: jekyll/minima
minima:
  skin: auto
header_pages:
  - blogs.md
  - resume.md
defaults:
  - scope:
      path: /assets/resume.pdf
    values:
      download: true
      external_url: /assets/resume.pdf
