title: My GitHub Pages Site
description: A simple site written with Markdown
theme: jekyll-theme-minimal

include:
  - _pages
  - _posts

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: true
